/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafic;

import java.util.List;
import javax.swing.DefaultListModel;
import javier.oobjetos.Tripulacion;
import javier.oobjetos.Vuelo;
import org.neodatis.odb.ODB;
import org.neodatis.odb.Objects;
import org.neodatis.odb.core.query.IQuery;
import org.neodatis.odb.impl.core.query.criteria.CriteriaQuery;

/**
 *
 * @author Alumno
 */
public class TripulacionVuelo extends javax.swing.JFrame {

    /**
     * Creates new form TripulacionVuelo
     */
    public TripulacionVuelo() {
        initComponents(); 
    }
    public TripulacionVuelo(MainWindow ventanaPrincipal) {
        initComponents();
        odb = ventanaPrincipal.getOdb();
        vuelo = ventanaPrincipal.vuelobuscado;
        this.addWindowListener(ventanaPrincipal); 
        cargarDatosIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListTripulantesDisponibles = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTripulantesAsignados = new javax.swing.JList<>();
        jButtonTodos = new javax.swing.JButton();
        jButtonAnadir = new javax.swing.JButton();
        jButtonQuitar = new javax.swing.JButton();
        jButtonQuitarTodos = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jListTripulantesDisponibles.setBorder(javax.swing.BorderFactory.createTitledBorder("Tripulantes disponibles"));
        jScrollPane1.setViewportView(jListTripulantesDisponibles);

        jListTripulantesAsignados.setBorder(javax.swing.BorderFactory.createTitledBorder("Tripulantes asignados"));
        jScrollPane2.setViewportView(jListTripulantesAsignados);

        jButtonTodos.setText("Añadir todos");
        jButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodosActionPerformed(evt);
            }
        });

        jButtonAnadir.setText("Añadir");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        jButtonQuitar.setText("Quitar");
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });

        jButtonQuitarTodos.setText("Quitar todos");
        jButtonQuitarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarTodosActionPerformed(evt);
            }
        });

        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAnadir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonQuitar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonQuitarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButtonFinalizar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQuitarTodos))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(jButtonFinalizar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        
        String nombre = jListTripulantesDisponibles.getSelectedValue();
        listaasignados.addElement(nombre);
        jListTripulantesAsignados.setModel(listaasignados);  
        listadisponibles.remove(jListTripulantesDisponibles.getSelectedIndex());
        jListTripulantesDisponibles.setModel(listadisponibles);       
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void jButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodosActionPerformed
        
        for(int i =0; i<listadisponibles.getSize();i++){

            String nombre = listadisponibles.get(i).toString();
            System.out.println(nombre);
            listaasignados.addElement(nombre);
        }
        jListTripulantesAsignados.setModel(listaasignados);  
        listadisponibles.removeAllElements();
        jListTripulantesDisponibles.setModel(listadisponibles);
    }//GEN-LAST:event_jButtonTodosActionPerformed

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        String nombre = jListTripulantesAsignados.getSelectedValue();
        listadisponibles.addElement(nombre);
        jListTripulantesDisponibles.setModel(listadisponibles);  
        listaasignados.remove(jListTripulantesAsignados.getSelectedIndex());
        jListTripulantesAsignados.setModel(listaasignados); 
    }//GEN-LAST:event_jButtonQuitarActionPerformed

    private void jButtonQuitarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarTodosActionPerformed
        for(int i =0; i<listaasignados.getSize();i++){

            String nombre = listaasignados.get(i).toString();
            listadisponibles.addElement(nombre);
        }
        jListTripulantesDisponibles.setModel(listadisponibles);  
        listaasignados.removeAllElements();
        jListTripulantesAsignados.setModel(listaasignados);
    }//GEN-LAST:event_jButtonQuitarTodosActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TripulacionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TripulacionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TripulacionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TripulacionVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TripulacionVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JButton jButtonQuitarTodos;
    private javax.swing.JButton jButtonTodos;
    private javax.swing.JList<String> jListTripulantesAsignados;
    private javax.swing.JList<String> jListTripulantesDisponibles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    ODB odb;
    Vuelo vuelo;
    DefaultListModel listadisponibles = new DefaultListModel();
    DefaultListModel listaasignados = new DefaultListModel();

    private void cargarDatosIniciales(){
        
        IQuery query = new CriteriaQuery(Tripulacion.class);
        Objects<Tripulacion> resultados = odb.getObjects(query);

        for (Tripulacion tripulante:resultados){

            listadisponibles.addElement(tripulante.getNombre());
        }
        jListTripulantesDisponibles.setModel(listadisponibles);
    }   
}
